### ISSUE TITLE
Duplicate themes

### ISSUE THREAD

**Issue by scottnath** [tonai/storybook-addon-themes#51] opened 2021-04-08 16:24 UTC
Hi,

I'm seeing the theme button twice in my toolbar.

I configured a theme in my preview.ts file:

```
addParameters({
  themes: [
    { class: 'ds-dark-theme', name: 'My Dark Theme' },
  ],
});
```

But I am ending up with two theme buttons in the toolbar. The other one looks to be the default theme. Is there a config I can set to turn off the default theme?

![Screen Shot 2021-04-08 at 12 23 23 PM](https://user-images.githubusercontent.com/216931/114062199-4021ae00-9865-11eb-80c5-aa5c00503b33.png)

thanks

**Comment by tonai** [comment] 2021-04-08 16:50
The button that allows you to switch to light or dark theme comes from another addon: https://storybook.js.org/docs/react/configure/theming

The problem is that we share the same icon, so it looks like a duplicate button, but the content of the dropdown should be different.

**Comment by tonai** [comment] 2021-07-28 13:18
Closing this as it would be solved with this issue: https://github.com/tonai/storybook-addon-themes/issues/50

**Closed as completed by tonai** 2021-07-28 13:18 UTC
