### ISSUE TITLE
Allow customization of theme line items

### ISSUE THREAD

**Issue by arosenb2** [tonai/storybook-addon-themes#14] opened 2019-11-06 05:22 UTC
Instead of only showing a name, it would be useful to optionally allow a component to be passed in and used for each theme line item

**Comment by tonai** [comment] 2019-11-06 23:08
Es that's a pretty good idea.
For now I prefer to focus on the issue #12 because it may have an impact on this one.

**Comment by tonai** [comment] 2020-01-30 15:53
Hi @arosenb2 I have some problems with that suggestion.

1. The problem is that the manager part of storybook (where you can find the list of your stories, addon panels, the theme button...etc.) is written in React.
And in the case you are using storybook with an other framework than React, you can't really write React in it.
In fact you can but without using JSX (by writting youself `React.createElement()`).
Or maybe you can by tweaking the webpack configuration to compile the JSX using React but in both cases that makes things really hard.

2. I tried to pass a function as a parameter when configuring the addon
 (inside the `addParameters` function) but when I get the function back, inside the code that renders the theme items in the manager, parameters get serialized and unserialized so the function is always empty.
So I think it is not possible to pass a component inside the parameters.
That means things get even more complicated for just that.

If you have any suggestions please tell me but for now I will close this issue.

**Closed as completed by tonai** 2020-01-30 15:53 UTC
Labels: enhancement
