### ISSUE TITLE
Proposal: include a specific CSS file per theme instead of adding a class

### ISSUE THREAD

**Issue by yguedidi** [tonai/storybook-addon-themes#21] opened 2020-02-27 18:40 UTC
I have several themes that are all basically overides of my global styles, but in separated files, with only one being loaded at the end.

Is this something doable?

**Comment by tonai** [comment] 2020-02-28 11:15
Hi @yguedidi,
in fact yes this is feasible.
Instead of a using the `class` property when declaring a theme we can for instance consider a `cssFile` property for that.

The little problem I see in that case is that, the handling of loading the CSS file must be done in the addon.
So what method should be used ?
* maybe sometimes you have your CSS file ready and you can load it through a `<link>` element
* maybe you use SCSS and want to import it and take advantage of webpack loaders
* maybe you use CSS in JS
* ...

I would prefer to opt for an option that can let you choose the method you want.
But the problem is that we can't pass fonction or components down with the theme configuration object...
Maybe there is some other way to do it. I have to check.

**Comment by tonai** [comment] 2020-03-05 15:58
Hi @yguedidi I just published a new version (5.4.0) that allow you to customize the decorator.

I have put an exemple in [the doc](https://github.com/tonai/storybook-addon-themes#custom-decorator) where I show how you can use a CSS file to update the theme using the `Decorator` option.

I think it should do what you want.

me know if it's ok for you.

**Comment by yguedidi** [comment] 2020-03-05 17:39
Hi @tonai! Thank you for your reactivity!
I don't think the custom decorator solution will solve my case, I'm using storybook/html, for which the decorator option isn't available.
The `cssFile` option that adds a `<link>` tag, handled by the addon, is the best option to me.

**Comment by CodeByAlex** [comment] 2020-03-19 19:41
@tonai - it looks like the addon doesnt support Angular - why is that so? Anything I can do to help - could really use that decorator

**Comment by tonai** [comment] 2020-03-19 20:50
Hi @CodeByAlex , the addon itself is compatible with Angular but without using the decorator.
If you need to use the decorator with Angular, can you please fill another issue ?

**Comment by CodeByAlex** [comment] 2020-03-19 20:51
Yes I need support for the decorator with Angular - will create an issue

**Comment by CodeByAlex** [comment] 2020-03-19 20:52
See #24

**Comment by tonai** [comment] 2020-03-24 17:57
Hi @yguedidi, I have created a branch `feat/html` with support the decorator for storybook HTML.
With this option you can provide a custom decorator to customize the way themes are handled.
I have added an axemple in the [README](https://github.com/tonai/storybook-addon-themes/blob/feat/html/README.md#html-example).

If you want to manage it globally you can create a file `.storybook/preview.js` with:
```js
import { withThemes } from 'storybook-addon-themes/html';
import { addParameters, addDecorator } from '@storybook/html'

function getOrCreate(id) {
  const elementOnDom = document.getElementById(id);
  if (elementOnDom) {
    return elementOnDom;
  }

  const element = document.createElement('link');
  element.setAttribute('id', id);
  element.setAttribute('rel', 'stylesheet');
  return element;
}

function Decorator(props) {
  const { children } = props;

  function setStyles({ theme, themeName }) {
    const link = getOrCreate('custom-stylesheet');
    if (!theme) {
      link.parentNode && link.parentNode.removeChild(link);
    } else {
      console.log(theme);
      link.href = theme.css;
      children.appendChild(link);
    }
  }
  setStyles(props);

  return [children, setStyles];
}

addDecorator(withThemes);
addParameters({
  themes: {
    Decorator,
    list: [
      { name: 'twitter', color: '#00aced', css: 'Button-twt.css' },
      { name: 'facebook', color: '#3b5998', css: 'Button-fb.css' },
    ]
  }
});
```
The branch is only compatible with the 6.x alpha version of storybook.

**Comment by CodeByAlex** [comment] 2020-03-25 04:02
@tonai - could you please send out a notification when this has been merged in. In addition to the Angular decorator (#24) need, the HTML version would also be helpful for one of our projects 😄

**Comment by Schum123** [comment] 2020-03-30 15:57
Would it be possible to add global stylesheet and not only for a single story, using vue? I tried looking at your branch `feat/html` but didnt come up with a solution.

**Comment by tonai** [comment] 2020-03-31 08:45
Hi @Schum123 for Vue you have to use the Vue decorator.

Setup your decorator globally : https://github.com/tonai/storybook-addon-themes#globally-1

Then use the a custom decorator using a Vue component:
```js
import { withThemes } from 'storybook-addon-themes/vue';

const Decorator = {
  props: ['themeName'],
  template: `
<div>
  <slot></slot>
  <link v-if="themeName === 'twitter'" rel="stylesheet" href="Button-twt.css"/>
  <link v-if="themeName === 'facebook'" rel="stylesheet" href="Button-fb.css"/>
</div>
`
};

export default {
  title: 'Button',
  component: MyButton,
  decorators: [ withThemes ],
  parameters: {
    themes: {
      Decorator,
      list: [
        { name: 'twitter', color: '#00aced', default: true },
        { name: 'facebook', color: '#3b5998' },
      ]
    }
  },
};
```

**Comment by Schum123** [comment] 2020-04-03 15:15
@tonai Yes! :smile:  Thank you very much!

**Comment by picapixa** [comment] 2021-02-27 14:46
@tonai Will `feat/html` be merged to `master`?

**Comment by tonai** [comment] 2021-03-10 17:25
Hello @picapixa I will need to rebase and check but yes I can try to merge it (in my mind it was already merged in fact...).

**Comment by tonai** [comment] 2021-03-10 17:36
Branch has been merged to master

**Closed as completed** 2021-03-10 17:35 UTC
Labels: enhancement

**Comment by webistomin** [comment] 2021-04-15 11:42
> Hi @Schum123 for Vue you have to use the Vue decorator.
> 
> Setup your decorator globally : https://github.com/tonai/storybook-addon-themes#globally-1
> 
> Then use the a custom decorator using a Vue component:
> 
> ```js
> import { withThemes } from 'storybook-addon-themes/vue';
> 
> const Decorator = {
>   props: ['themeName'],
>   template: `
> <div>
>   <slot></slot>
>   <link v-if="themeName === 'twitter'" rel="stylesheet" href="Button-twt.css"/>
>   <link v-if="themeName === 'facebook'" rel="stylesheet" href="Button-fb.css"/>
> </div>
> `
> };
> 
> export default {
>   title: 'Button',
>   component: MyButton,
>   decorators: [ withThemes ],
>   parameters: {
>     themes: {
>       Decorator,
>       list: [
>         { name: 'twitter', color: '#00aced', default: true },
>         { name: 'facebook', color: '#3b5998' },
>       ]
>     }
>   },
> };
> ```

Do you have any idea how to do something similar, but using sass?

**Comment by ChristopherJohnson25** [comment] 2022-11-03 17:49
Could you set this up globally on preview.cjs?
